export const ARTICLE_UPVOTE = 'ARTICLE/UPVOTE';

export const LOADING = 'LOADING';

export const ARTICLE_CREATE = 'ARTICLE/CREATE';

export const ARTICLE_COMMENT = 'ARTICLE/COMMENT';

export const ARTICLE_RETRIEVE = 'ARTICLE/RETRIEVE';

export const ARTICLE_GET = 'ARTICLE/GET';